import {
  Container as UIContainer,
  Autocomplete as UIAutocomplete,
  Grid as UIGrid,
  TextField as UITextField,
  Avatar as UIAvatar,
  IconButton as UIIconButton,
  Divider as UIDivider,
  Typography as UITypography,
  List as UIList,
  ListItemButton as UIListItemButton,
  ListItemIcon as UIListItemIcon,
  Collapse as UICollapse,
  ListItemText as UIListItemText,
  Drawer as UIDrawer,
  CssBaseline as UICssBaseline,
  Toolbar as UIToolbar,
  Dialog as UIDialog,
  DialogTitle as UIDialogTitle,
  DialogContent as UIDialogContent,
  DialogActions as UIDialogActions,
  MenuItem as UIMenuItem,
  Accordion as UIAccordion,
  AccordionSummary as UIAccordionSummary,
  AccordionDetails as UIAccordionDetails,
  Tabs as UITabs,
  Tab as UITab,
  ToggleButton as UIToggleButton,
  ToggleButtonGroup as UIToggleButtonGroup,
  Button as UIButton,
  Box as UIBox,
  Input as UIInput,
  Card as UICard,
  CardActions as UICardActions,
  CardContent as UICardContent,
  AppBar as UIAppBar,
  Checkbox as UICheckbox,
  TextareaAutosize as UITextareaAutosize,
} from "@mui/material";

import { DataGridPro, GridToolbar } from "@mui/x-data-grid-pro";
import { GridActionsCellItem } from "@mui/x-data-grid";
import {
  TabContext as UITabContext,
  TabList as UITabList,
  TabPanel as UITabPanel,
} from "@mui/lab";

import {
  DatePicker as UIDatePicker,
  LocalizationProvider as UILocalizationProvider,
} from "@mui/x-date-pickers";
import { AdapterDayjs as UIAdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";

const MuiModules = {
  UIContainer,
  UIAutocomplete,
  UIGrid,
  UITextField,
  UIAvatar,
  UIBox,
  UICollapse,
  UIListItemText,
  UIDrawer,
  UICssBaseline,
  UIToolbar,
  UITypography,
  UIList,
  UIDivider,
  UIIconButton,
  UIListItemButton,
  UIListItemIcon,
  UIDialog,
  UIDialogTitle,
  UIDialogContent,
  UIDialogActions,
  UIMenuItem,
  UIAccordion,
  UIAccordionSummary,
  UIAccordionDetails,
  UITabs,
  UITab,
  UIToggleButton,
  UIToggleButtonGroup,
  UIButton,
  UICheckbox,
  UIInput,
  DataGridPro,
  GridToolbar,
  GridActionsCellItem,
  UITabContext,
  UITabList,
  UITabPanel,
  UIDatePicker,
  UILocalizationProvider,
  UIAdapterDayjs,
  UICard,
  UICardActions,
  UICardContent,
  UIAppBar,
  UITextareaAutosize,
};

export default MuiModules;
